/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Create: (typeof import('./src/components/Create/index.vue'))['default']
    Editor: (typeof import('./src/components/Editor/index.vue'))['default']
    Footer: (typeof import('./src/components/Footer/index.vue'))['default']
    Header: (typeof import('./src/components/Header/index.vue'))['default']
    HelloWorld: (typeof import('./src/components/Preview/HelloWorld.vue'))['default']
    NButton: (typeof import('naive-ui'))['NButton']
    NConfigProvider: (typeof import('naive-ui'))['NConfigProvider']
    NLayout: (typeof import('naive-ui'))['NLayout']
    NLayoutFooter: (typeof import('naive-ui'))['NLayoutFooter']
    NLayoutHeader: (typeof import('naive-ui'))['NLayoutHeader']
    NSpace: (typeof import('naive-ui'))['NSpace']
    NSplit: (typeof import('naive-ui'))['NSplit']
    NTooltip: (typeof import('naive-ui'))['NTooltip']
    Operate: (typeof import('./src/components/Operate/index.vue'))['default']
    Preview: (typeof import('./src/components/Preview/index.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    ViewDetail: (typeof import('./src/components/Preview/viewDetail.vue'))['default']
  }
}
